[package]
name = "aoc2023"
version = "0.1.0"
authors = ["Alperen Guncan"]
default-run = "aoc2023"
edition = "2021"

[dependencies]
itertools = "0.10"
hashbrown = "0.13"
serde_json = "1.0"
rayon = "1.6"
clap = { version = "4.4.9", features = ["derive"] }
